/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/attendeefemaleavatar1.gltf
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from '@react-three/drei'
import { useAvatarCustomization } from "contexts/AvatarCustomizationContext";

const Attendeefemaleavatar1=(props) =>{
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    "./models/attendeefemaleavatar1.gltf"
  );
  const { actions,names } = useAnimations(animations, group)

   const {
     hairColor,
     setHairColor,
     shirtColor,
     setShirtColor,
     pantsColor,
     setPantsColor,
     shoesColor,
     setShoesColor,
     skinColor,
     setSkinColor,
   } = useAvatarCustomization();
   
   useEffect(() => {
     actions[names[0]].reset().fadeIn(0.5).play();
   }, []);
  
 useEffect(() => {
   setHairColor(`#${materials.Ch22_hair.color.getHexString()}`);
   setSkinColor(`#${materials.Ch22_body.color.getHexString()}`);
   setShirtColor(`#${materials.Ch22_body.color.getHexString()}`);
   setPantsColor(`#${materials.Ch22_body.color.getHexString()}`);
   setShoesColor(`#${materials.Ch22_body.color.getHexString()}`);
 }, []);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig2Hips} />
          <skinnedMesh
            name="Ch22_Body"
            geometry={nodes.Ch22_Body.geometry}
            material={materials.Ch22_body}
            skeleton={nodes.Ch22_Body.skeleton}
          >
            <meshStandardMaterial {...materials.Ch22_body} color={skinColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Ch22_Eyelashes"
            geometry={nodes.Ch22_Eyelashes.geometry}
            material={materials.Ch22_hair}
            skeleton={nodes.Ch22_Eyelashes.skeleton}
          />

          <skinnedMesh
            name="Ch22_Hair"
            geometry={nodes.Ch22_Hair.geometry}
            material={materials.Ch22_hair}
            skeleton={nodes.Ch22_Hair.skeleton}
          >
            <meshStandardMaterial {...materials.Ch22_hair} color={hairColor} />
          </skinnedMesh>

          <skinnedMesh
            name="Ch22_Pants"
            geometry={nodes.Ch22_Pants.geometry}
            material={materials.Ch22_body}
            skeleton={nodes.Ch22_Pants.skeleton}
          >
            <meshStandardMaterial {...materials.Ch22_body} color={pantsColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Ch22_Shirt"
            geometry={nodes.Ch22_Shirt.geometry}
            material={materials.Ch22_body}
            skeleton={nodes.Ch22_Shirt.skeleton}
          >
            <meshStandardMaterial {...materials.Ch22_body} color={shirtColor} />
          </skinnedMesh>

          <skinnedMesh
            name="Ch22_Sneakers"
            geometry={nodes.Ch22_Sneakers.geometry}
            material={materials.Ch22_body}
            skeleton={nodes.Ch22_Sneakers.skeleton}
          >
            <meshStandardMaterial {...materials.Ch22_body} color={shoesColor} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
}

export default Attendeefemaleavatar1;
useGLTF.preload(".models/attendeefemaleavatar1.gltf");
