/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/attendeemaleavatar21.gltf
*/

import React, { useEffect,useRef } from "react";
import { useGLTF, useAnimations } from '@react-three/drei'
import { useAvatarCustomization } from "contexts/AvatarCustomizationContext";

const Attendeemaleavatar2 = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./avatars/attendeemaleavatar2.gltf"
  );
  const { actions, names } = useAnimations(animations, group);

  const {
    hairColor,
    setHairColor,
    shirtColor,
    setShirtColor,
    pantsColor,
    setPantsColor,
    shoesColor,
    setShoesColor,
    skinColor,
    setSkinColor,
  } = useAvatarCustomization();

  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);

  useEffect(() => {
    setHairColor(`#${materials.Ch08_hair.color.getHexString()}`);
    setSkinColor(`#${materials.Ch08_body1.color.getHexString()}`);
    setShirtColor(`#${materials.Ch08_body1.color.getHexString()}`);
    setPantsColor(`#${materials.Ch08_body1.color.getHexString()}`);
    setShoesColor(`#${materials.Ch08_body1.color.getHexString()}`);
  }, []);  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig7Hips} />
          <skinnedMesh
            name="Ch08_Beard"
            geometry={nodes.Ch08_Beard.geometry}
            material={materials.Ch08_hair}
            skeleton={nodes.Ch08_Beard.skeleton}
          >
            <meshStandardMaterial {...materials.Ch08_hair} color={hairColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Ch08_Body"
            geometry={nodes.Ch08_Body.geometry}
            material={materials.Ch08_body}
            skeleton={nodes.Ch08_Body.skeleton}
          >
            <meshStandardMaterial {...materials.Ch08_body} color={skinColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Ch08_Eyelashes"
            geometry={nodes.Ch08_Eyelashes.geometry}
            material={materials.Ch08_hair}
            skeleton={nodes.Ch08_Eyelashes.skeleton}
          />
          <skinnedMesh
            name="Ch08_Hair"
            geometry={nodes.Ch08_Hair.geometry}
            material={materials.Ch08_hair}
            skeleton={nodes.Ch08_Hair.skeleton}
          >
            <meshStandardMaterial {...materials.Ch08_hair} color={hairColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Ch08_Hoodie"
            geometry={nodes.Ch08_Hoodie.geometry}
            material={materials.Ch08_body1}
            skeleton={nodes.Ch08_Hoodie.skeleton}
          >
            <meshStandardMaterial {...materials.Ch08_body1} color={shirtColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Ch08_Pants"
            geometry={nodes.Ch08_Pants.geometry}
            material={materials.Ch08_body1}
            skeleton={nodes.Ch08_Pants.skeleton}
          >
            <meshStandardMaterial {...materials.Ch08_body1} color={pantsColor} />
          </skinnedMesh>
          <skinnedMesh
            name="Ch08_Sneakers"
            geometry={nodes.Ch08_Sneakers.geometry}
            material={materials.Ch08_body1}
            skeleton={nodes.Ch08_Sneakers.skeleton}
          >
            <meshStandardMaterial {...materials.Ch08_body1} color={shoesColor} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
};
export default Attendeemaleavatar2;
useGLTF.preload('./avatars/attendeemaleavatar21.gltf')
