/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/stalls/diamondStall.gltf
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useStallCustomization } from "contexts/StallCustomizationContext";

const DiamondStall = (props) => {
  const { nodes, materials } = useGLTF("./stalls/diamondStall.gltf");

  const { stallColor, setStallColor } = useStallCustomization();

  useEffect(() => {
    if (stallColor == null) {
      setStallColor(`#${materials.Diamond_2.color.getHexString()}`);
    }
  }, []);

  // useEffect(() => {
  //   setStallColor(`#${materials.Diamond_2.color.getHexString()}`);
  // }, []);

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001}>
        <group
          position={[-795, -651, 1.52]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.7, 1, 1]}
        >
          <group position={[-679, 940, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.chair_for_the_client.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[1113.8, 413, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__10_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[755, 492.4, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__11_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[755, 413, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__12_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[935.7, 996.1, -8.7]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__1_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[1113.8, 492.4, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__2_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[1113.8, 563.2, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__3_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[1113.8, 641.2, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__4_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[1113.8, 704.3, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__5_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[1113.8, 771.2, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__6_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[755, 771.2, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__7_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[755, 704.3, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__8_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[755, 641.2, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__9_.geometry}
              material={materials.chair_for_the_client_default_color}
              position={[755, 563.2, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Notebook.geometry}
              material={materials.Notebook}
              position={[1014.4, 777.7, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__10_.geometry}
              material={materials.Notebook}
              position={[871, 716.1, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_10.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__11_.geometry}
              material={materials.Notebook}
              position={[871, 777.7, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_11.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__1_.geometry}
              material={materials.Notebook}
              position={[1014.4, 716.1, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_1.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__2_.geometry}
              material={materials.Notebook}
              position={[1014.4, 654.1, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_2.geometry}
                material={materials.Notebook}
                position={[-14.2, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__3_.geometry}
              material={materials.Notebook}
              position={[1014.4, 580.3, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_3.geometry}
                material={materials.Notebook}
                position={[-14.2, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__4_.geometry}
              material={materials.Notebook}
              position={[1014.4, 501.5, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_4.geometry}
                material={materials.Notebook}
                position={[-14.2, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__5_.geometry}
              material={materials.Notebook}
              position={[1014.4, 420.4, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_5.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__6_.geometry}
              material={materials.Notebook}
              position={[871, 420.4, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_6.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__7_.geometry}
              material={materials.Notebook}
              position={[871, 501.5, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_7.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__8_.geometry}
              material={materials.Notebook}
              position={[871, 580.3, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_8.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__9_.geometry}
              material={materials.Notebook}
              position={[871, 654.1, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_9.geometry}
                material={materials.Notebook}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <group position={[727.1, 1097.2, -11]}>
              <mesh
                geometry={nodes.Scene009.geometry}
                material={materials.metal}
              />
              <mesh
                geometry={nodes.Scene009_1.geometry}
                material={materials.glass}
              />
            </group>
            <group position={[1263, 1097, -11]}>
              <mesh
                geometry={nodes.Scene009.geometry}
                material={materials.metal}
              />
              <mesh
                geometry={nodes.Scene009_1.geometry}
                material={materials.glass}
              />
            </group>
            <group position={[1835, 1097, -11]}>
              <mesh
                geometry={nodes.Scene009.geometry}
                material={materials.metal}
              />
              <mesh
                geometry={nodes.Scene009_1.geometry}
                material={materials.glass}
              />
            </group>
          </group>
          <mesh geometry={nodes.Scene011.geometry} material={materials.black} />
          <mesh
            geometry={nodes.Scene011_1.geometry}
            material={materials.Diamond_2}
          >
            <meshStandardMaterial {...materials.Diamond_2} color={stallColor} />
          </mesh>
        </group>
        <group position={[-444, 4, -181]} scale={[1, 4, 3]}>
          <mesh geometry={nodes.TV_1.geometry} material={materials.TV} />
          <mesh
            geometry={nodes.TV_screen.geometry}
            material={materials.TV_screen}
          />
        </group>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.black}
          position={[2, -591, -6]}
          scale={[9.96, 7, 0.14]}
        />
        <group
          position={[-804.12, -31.2, 0]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.7, 1.1, 0.95]}
        >
          <mesh geometry={nodes.Scene002.geometry} material={materials.black} />
          <mesh
            geometry={nodes.Scene002_1.geometry}
            material={materials.Diamond_2}
          >
            <meshStandardMaterial {...materials.Diamond_2} color={stallColor} />
          </mesh>
          <group position={[-160, -44, 1.59]} scale={[1.42, 0.91, 1.05]}>
            <group position={[223.8, 351.3, -317.6]}>
              <group position={[3.9, 0, 0]}>
                <mesh
                  geometry={nodes.Scene007.geometry}
                  material={materials.white}
                />
                <mesh
                  geometry={nodes.Scene007_1.geometry}
                  material={materials.black}
                />
                <mesh
                  geometry={nodes.Scene007_2.geometry}
                  material={materials.light}
                />
                <mesh
                  geometry={nodes.Scene007_3.geometry}
                  material={materials.chrome}
                />
              </group>
              <group position={[-0.7, 0, 0]}>
                <mesh
                  geometry={nodes.Scene008.geometry}
                  material={materials.white}
                />
                <mesh
                  geometry={nodes.Scene008_1.geometry}
                  material={materials.chrome}
                />
                <mesh
                  geometry={nodes.Scene008_2.geometry}
                  material={materials.black}
                />
                <mesh
                  geometry={nodes.Scene008_3.geometry}
                  material={materials.light}
                />
              </group>
              <group position={[-439.3, 0, 0]}>
                <mesh
                  geometry={nodes.Scene008.geometry}
                  material={materials.white}
                />
                <mesh
                  geometry={nodes.Scene008_1.geometry}
                  material={materials.chrome}
                />
                <mesh
                  geometry={nodes.Scene008_2.geometry}
                  material={materials.black}
                />
                <mesh
                  geometry={nodes.Scene008_3.geometry}
                  material={materials.light}
                />
              </group>
            </group>
            <group position={[226, -255, -317.6]}>
              <group position={[-1.8, 0, 0]}>
                <mesh
                  geometry={nodes.Scene008.geometry}
                  material={materials.white}
                />
                <mesh
                  geometry={nodes.Scene008_1.geometry}
                  material={materials.chrome}
                />
                <mesh
                  geometry={nodes.Scene008_2.geometry}
                  material={materials.black}
                />
                <mesh
                  geometry={nodes.Scene008_3.geometry}
                  material={materials.light}
                />
              </group>
              <group position={[-427.6, 0, 0]}>
                <mesh
                  geometry={nodes.Scene008.geometry}
                  material={materials.white}
                />
                <mesh
                  geometry={nodes.Scene008_1.geometry}
                  material={materials.chrome}
                />
                <mesh
                  geometry={nodes.Scene008_2.geometry}
                  material={materials.black}
                />
                <mesh
                  geometry={nodes.Scene008_3.geometry}
                  material={materials.light}
                />
              </group>
              <mesh
                geometry={nodes.Scene007.geometry}
                material={materials.white}
              />
              <mesh
                geometry={nodes.Scene007_1.geometry}
                material={materials.black}
              />
              <mesh
                geometry={nodes.Scene007_2.geometry}
                material={materials.light}
              />
              <mesh
                geometry={nodes.Scene007_3.geometry}
                material={materials.chrome}
              />
            </group>
            <group position={[-121, 177, -8]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh
                geometry={nodes.pouf_1_1.geometry}
                material={materials.pouf}
              />
              <mesh
                geometry={nodes.pouf_1__1__1.geometry}
                material={materials.pouf}
                position={[361.96, -0.71, 0]}
                rotation={[0, 0, -1.79]}
              />
              <mesh
                geometry={nodes.pouf_2_1.geometry}
                material={materials.pouf_2}
                position={[119.6, -1.6, 0]}
                rotation={[0, 0, -1.63]}
              />
              <mesh
                geometry={nodes.pouf_2__1__1.geometry}
                material={materials.pouf_2}
                position={[232.9, -0.53, 0]}
                rotation={[0, 0, -1.91]}
              />
            </group>
            <group
              position={[-580.3, 2289.3, -0.2]}
              rotation={[0, 0, -Math.PI / 2]}
            >
              <group position={[2185.9, 796.7, -109.8]}>
                <mesh
                  geometry={nodes.Scene003.geometry}
                  material={materials.TV}
                />
                <mesh
                  geometry={nodes.Scene003_1.geometry}
                  material={materials.TV_screen}
                />
              </group>
              <group position={[2297.6, 796.7, -109.8]}>
                <mesh
                  geometry={nodes.Scene003.geometry}
                  material={materials.TV}
                />
                <mesh
                  geometry={nodes.Scene003_1.geometry}
                  material={materials.TV_screen}
                />
              </group>
              <group
                position={[2297.6, 698.3, -109.8]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.Scene003.geometry}
                  material={materials.TV}
                />
                <mesh
                  geometry={nodes.Scene003_1.geometry}
                  material={materials.TV_screen}
                />
              </group>
              <group
                position={[2185.9, 695.9, -109.8]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.Scene003.geometry}
                  material={materials.TV}
                />
                <mesh
                  geometry={nodes.Scene003_1.geometry}
                  material={materials.TV_screen}
                />
              </group>
              <group
                position={[2316.5, 749.6, -109.8]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.Scene003.geometry}
                  material={materials.TV}
                />
                <mesh
                  geometry={nodes.Scene003_1.geometry}
                  material={materials.TV_screen}
                />
              </group>
              <group
                position={[2151.6, 737.7, -109.8]}
                rotation={[0, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.Scene003.geometry}
                  material={materials.TV}
                />
                <mesh
                  geometry={nodes.Scene003_1.geometry}
                  material={materials.TV_screen}
                />
              </group>
            </group>
            <mesh
              geometry={nodes.Chair_2_1.geometry}
              material={materials.Chair_2}
              position={[330.3, -94.1, -7.3]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Chair_2__1__1.geometry}
              material={materials.Chair_2}
              position={[330.3, 54, -7.3]}
              rotation={[0, 0, -Math.PI / 2]}
            />
          </group>
        </group>
        <mesh geometry={nodes.Scene002.geometry} material={materials.black} />
        <mesh
          geometry={nodes.Scene002_1.geometry}
          material={materials.Diamond_2}
        >
          <meshStandardMaterial {...materials.Diamond_2} color={stallColor} />
        </mesh>
        <group position={[0, 17, 1.52]}>
          <group position={[160, 258, -317.6]}>
            <group position={[1, 0, 0]}>
              <mesh
                geometry={nodes.Scene008.geometry}
                material={materials.white}
              />
              <mesh
                geometry={nodes.Scene008_1.geometry}
                material={materials.chrome}
              />
              <mesh
                geometry={nodes.Scene008_2.geometry}
                material={materials.black}
              />
              <mesh
                geometry={nodes.Scene008_3.geometry}
                material={materials.light}
              />
            </group>
            <group position={[-619.1, 0, 0]}>
              <mesh
                geometry={nodes.Scene008.geometry}
                material={materials.white}
              />
              <mesh
                geometry={nodes.Scene008_1.geometry}
                material={materials.chrome}
              />
              <mesh
                geometry={nodes.Scene008_2.geometry}
                material={materials.black}
              />
              <mesh
                geometry={nodes.Scene008_3.geometry}
                material={materials.light}
              />
            </group>
            <mesh
              geometry={nodes.Scene007.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Scene007_1.geometry}
              material={materials.black}
            />
            <mesh
              geometry={nodes.Scene007_2.geometry}
              material={materials.light}
            />
            <mesh
              geometry={nodes.Scene007_3.geometry}
              material={materials.chrome}
            />
          </group>
          <group position={[160, -292, -317.6]}>
            <group position={[1, 0, 0]}>
              <mesh
                geometry={nodes.Scene008.geometry}
                material={materials.white}
              />
              <mesh
                geometry={nodes.Scene008_1.geometry}
                material={materials.chrome}
              />
              <mesh
                geometry={nodes.Scene008_2.geometry}
                material={materials.black}
              />
              <mesh
                geometry={nodes.Scene008_3.geometry}
                material={materials.light}
              />
            </group>
            <group position={[-619.1, 0, 0]}>
              <mesh
                geometry={nodes.Scene008.geometry}
                material={materials.white}
              />
              <mesh
                geometry={nodes.Scene008_1.geometry}
                material={materials.chrome}
              />
              <mesh
                geometry={nodes.Scene008_2.geometry}
                material={materials.black}
              />
              <mesh
                geometry={nodes.Scene008_3.geometry}
                material={materials.light}
              />
            </group>
            <mesh
              geometry={nodes.Scene007.geometry}
              material={materials.white}
            />
            <mesh
              geometry={nodes.Scene007_1.geometry}
              material={materials.black}
            />
            <mesh
              geometry={nodes.Scene007_2.geometry}
              material={materials.light}
            />
            <mesh
              geometry={nodes.Scene007_3.geometry}
              material={materials.chrome}
            />
          </group>
          <group position={[-368.6, 177, -8]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.pouf_1.geometry} material={materials.pouf} />
            <mesh
              geometry={nodes.pouf_1__1_.geometry}
              material={materials.pouf}
              position={[361.96, -0.71, 0]}
              rotation={[0, 0, -1.79]}
            />
            <mesh
              geometry={nodes.pouf_2.geometry}
              material={materials.pouf_2}
              position={[119.6, -1.6, 0]}
              rotation={[0, 0, -1.63]}
            />
            <mesh
              geometry={nodes.pouf_2__1_.geometry}
              material={materials.pouf_2}
              position={[232.9, -0.53, 0]}
              rotation={[0, 0, -1.91]}
            />
          </group>
          <group
            position={[-649, 2224.8, -0.2]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <group position={[2185.9, 796.7, -109.8]}>
              <mesh
                geometry={nodes.Scene003.geometry}
                material={materials.TV}
              />
              <mesh
                geometry={nodes.Scene003_1.geometry}
                material={materials.TV_screen}
              />
            </group>
            <group position={[2297.6, 796.7, -109.8]}>
              <mesh
                geometry={nodes.Scene003.geometry}
                material={materials.TV}
              />
              <mesh
                geometry={nodes.Scene003_1.geometry}
                material={materials.TV_screen}
              />
            </group>
            <group position={[2297.6, 653, -109.8]} rotation={[0, 0, -Math.PI]}>
              <mesh
                geometry={nodes.Scene003.geometry}
                material={materials.TV}
              />
              <mesh
                geometry={nodes.Scene003_1.geometry}
                material={materials.TV_screen}
              />
            </group>
            <group position={[2185.9, 653, -109.8]} rotation={[0, 0, -Math.PI]}>
              <mesh
                geometry={nodes.Scene003.geometry}
                material={materials.TV}
              />
              <mesh
                geometry={nodes.Scene003_1.geometry}
                material={materials.TV_screen}
              />
            </group>
            <group
              position={[2316.5, 715.6, -109.8]}
              rotation={[0, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Scene003.geometry}
                material={materials.TV}
              />
              <mesh
                geometry={nodes.Scene003_1.geometry}
                material={materials.TV_screen}
              />
            </group>
            <group
              position={[2168.9, 715.6, -109.8]}
              rotation={[0, 0, Math.PI / 2]}
            >
              <mesh
                geometry={nodes.Scene003.geometry}
                material={materials.TV}
              />
              <mesh
                geometry={nodes.Scene003_1.geometry}
                material={materials.TV_screen}
              />
            </group>
          </group>
          <group position={[453, -873, -10.3]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Scene009.geometry}
              material={materials.metal}
            />
            <mesh
              geometry={nodes.Scene009_1.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[453, 231, -10.3]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Scene009.geometry}
              material={materials.metal}
            />
            <mesh
              geometry={nodes.Scene009_1.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[453, -335, -10.3]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh
              geometry={nodes.Scene009.geometry}
              material={materials.metal}
            />
            <mesh
              geometry={nodes.Scene009_1.geometry}
              material={materials.glass}
            />
          </group>
          <mesh
            geometry={nodes.Chair_2.geometry}
            material={materials.Chair_2}
            position={[330.3, -94.1, -7.3]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Chair_2__1_.geometry}
            material={materials.Chair_2}
            position={[330.3, 54, -7.3]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </group>
      </group>
    </group>
  );
};

export default DiamondStall;

useGLTF.preload(".stalls/diamondStall.gltf");
