/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/stalls/platinumStall.gltf
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useStallCustomization } from "contexts/StallCustomizationContext";

const PlatinumStall = (props) => {
  const { nodes, materials } = useGLTF("./stalls/platinumStall.gltf");
  const { stallColor, setStallColor } = useStallCustomization();

    useEffect(() => {
      setStallColor(`#${materials.Platinum.color.getHexString()}`);
    }, []);
  return (
    <group {...props} dispose={null}>
      <group position={[-679, 940, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <group position={[727.1, 1097.2, -11]}>
          <mesh geometry={nodes.Scene009.geometry} material={materials.metal} />
          <mesh
            geometry={nodes.Scene009_1.geometry}
            material={materials.glass}
          />
        </group>
        <mesh
          geometry={nodes.chair_for_the_client__12_.geometry}
          material={materials.chair_for_the_client_default_color}
          position={[935.7, 996.1, -8.7]}
        />
        <mesh
          geometry={nodes.chair_for_the_client__6_.geometry}
          material={materials.chair_for_the_client_default_color}
          position={[755, 771.2, -8.7]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.chair_for_the_client__7_.geometry}
          material={materials.chair_for_the_client_default_color}
          position={[755, 704.3, -8.7]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.chair_for_the_client__8_.geometry}
          material={materials.chair_for_the_client_default_color}
          position={[755, 641.2, -8.7]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.chair_for_the_client__9_.geometry}
          material={materials.chair_for_the_client_default_color}
          position={[755, 563.2, -8.7]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Notebook__10_.geometry}
          material={materials.Notebook}
          position={[871, 716.1, -109.5]}
          rotation={[0, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes.Notebook_Cap_10.geometry}
            material={materials.Notebook}
            position={[-14.19, 0, -0.69]}
          />
        </mesh>
        <mesh
          geometry={nodes.Notebook__11_.geometry}
          material={materials.Notebook}
          position={[871, 777.7, -109.5]}
          rotation={[0, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes.Notebook_Cap_11.geometry}
            material={materials.Notebook}
            position={[-14.19, 0, -0.69]}
          />
        </mesh>
        <mesh
          geometry={nodes.Notebook__9_.geometry}
          material={materials.Notebook}
          position={[871, 654.1, -109.5]}
          rotation={[0, 0, -Math.PI]}
        >
          <mesh
            geometry={nodes.Notebook_Cap_9.geometry}
            material={materials.Notebook}
            position={[-14.19, 0, -0.69]}
          />
        </mesh>
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[783, 246, -343]} rotation={[0, 0, Math.PI / 2]}>
          <mesh
            geometry={nodes.logo_1.geometry}
            material={materials.LiberationSans_SDF_Material}
            position={[14, 0, -119]}
            rotation={[0, 0, -Math.PI]}
          />
        </group>
        <group position={[1095, -160, 11.88]} rotation={[0, 0, Math.PI / 2]}>
          <group
            position={[-601, 951.7, -16.9]}
            rotation={[0, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes.chair_for_the_client.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[1113.8, 413, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__10_.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[755, 492.4, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__11_.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[755, 413, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__12_001.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[935.7, 996.1, -8.7]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__1_.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[1113.8, 492.4, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__2_.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[1113.8, 563.2, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__3_.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[1113.8, 641.2, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__4_.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[1113.8, 704.3, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__5_.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[1113.8, 771.2, -8.7]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__6_001.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[755, 771.2, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__7_001.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[755, 704.3, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__8_001.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[755, 641.2, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.chair_for_the_client__9_001.geometry}
              material={materials["chair_for_the_client_default_color.001"]}
              position={[755, 563.2, -8.7]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Notebook.geometry}
              material={materials["Notebook.001"]}
              position={[1014.4, 777.7, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__10_001.geometry}
              material={materials["Notebook.001"]}
              position={[871, 716.1, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_10001.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__11_001.geometry}
              material={materials["Notebook.001"]}
              position={[871, 777.7, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_11001.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__1_.geometry}
              material={materials["Notebook.001"]}
              position={[1014.4, 716.1, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_1.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__2_.geometry}
              material={materials["Notebook.001"]}
              position={[1014.4, 654.1, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_2.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__3_.geometry}
              material={materials["Notebook.001"]}
              position={[1014.4, 580.3, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_3.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__4_.geometry}
              material={materials["Notebook.001"]}
              position={[1014.4, 501.5, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_4.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__5_.geometry}
              material={materials["Notebook.001"]}
              position={[1014.4, 420.4, -109.5]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_5.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__6_.geometry}
              material={materials["Notebook.001"]}
              position={[871, 420.4, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_6.geometry}
                material={materials["Notebook.001"]}
                position={[-14.2, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__7_.geometry}
              material={materials["Notebook.001"]}
              position={[871, 501.5, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_7.geometry}
                material={materials["Notebook.001"]}
                position={[-14.2, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__8_.geometry}
              material={materials["Notebook.001"]}
              position={[871, 580.3, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_8.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <mesh
              geometry={nodes.Notebook__9_001.geometry}
              material={materials["Notebook.001"]}
              position={[871, 654.1, -109.5]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Notebook_Cap_9001.geometry}
                material={materials["Notebook.001"]}
                position={[-14.19, 0, -0.69]}
              />
            </mesh>
            <group position={[727.1, 1097.2, -11]}>
              <mesh
                geometry={nodes.Scene018.geometry}
                material={materials["metal.001"]}
              />
              <mesh
                geometry={nodes.Scene018_1.geometry}
                material={materials["glass.001"]}
              />
            </group>
            <group position={[1137, 1097.2, -11]}>
              <mesh
                geometry={nodes.Scene018.geometry}
                material={materials["metal.001"]}
              />
              <mesh
                geometry={nodes.Scene018_1.geometry}
                material={materials["glass.001"]}
              />
            </group>
          </group>
          <group position={[75, 9, -13]} scale={[1.05, 0.97, 1.02]}>
            <mesh
              geometry={nodes.Scene024.geometry}
              material={materials["black.001"]}
            />
            <mesh
              geometry={nodes.Scene024_1.geometry}
              material={materials.Platinum}
            >
              <meshStandardMaterial
                {...materials.Platinum}
                color={stallColor}
              />
            </mesh>
          </group>
        </group>
        <group
          position={[344, -332.87, -168]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[1, 4, 3]}
        >
          <mesh geometry={nodes.TV_1.geometry} material={materials["TV.001"]} />
          <mesh
            geometry={nodes.TV_screen.geometry}
            material={materials["TV_screen.001"]}
          />
        </group>
        <mesh geometry={nodes.Scene017.geometry} material={materials.red} />
        <mesh
          geometry={nodes.Scene017_1.geometry}
          material={materials.Platinum}
        >
          <meshStandardMaterial {...materials.Platinum} color={stallColor} />
        </mesh>
        <mesh geometry={nodes.Scene017_2.geometry} material={materials.blue} />
        <mesh
          geometry={nodes.Scene017_3.geometry}
          material={materials["black.001"]}
        />
        <group position={[1029, 5194, 0]} rotation={[0, 0, Math.PI / 2]}>
          <group position={[-5449.9, 1479.8, -249]}>
            <group position={[650, -1248.3, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh
                geometry={nodes.Scene022.geometry}
                material={materials["white.001"]}
              />
              <mesh
                geometry={nodes.Scene022_1.geometry}
                material={materials["black.001"]}
              />
              <mesh
                geometry={nodes.Scene022_2.geometry}
                material={materials["light.001"]}
              />
              <mesh
                geometry={nodes.Scene022_3.geometry}
                material={materials["chrome.001"]}
              />
            </group>
            <group position={[157, -1248.3, 0]} rotation={[0, 0, -Math.PI / 2]}>
              <mesh
                geometry={nodes.Scene022.geometry}
                material={materials["white.001"]}
              />
              <mesh
                geometry={nodes.Scene022_1.geometry}
                material={materials["black.001"]}
              />
              <mesh
                geometry={nodes.Scene022_2.geometry}
                material={materials["light.001"]}
              />
              <mesh
                geometry={nodes.Scene022_3.geometry}
                material={materials["chrome.001"]}
              />
            </group>
          </group>
          <group position={[-5375.7, 732.3, -9.4]} scale={1.2}>
            <mesh
              geometry={nodes.round_coffee_table_001.geometry}
              material={materials["glass.001"]}
            />
            <mesh
              geometry={nodes.round_coffee_table_1.geometry}
              material={materials.round_coffee_table}
            />
          </group>
          <group position={[-5025.2, 408.5, -9.4]} scale={1.2}>
            <mesh
              geometry={nodes.round_coffee_table_001_1.geometry}
              material={materials["glass.001"]}
            />
            <mesh
              geometry={nodes.round_coffee_table_2.geometry}
              material={materials.round_coffee_table}
            />
          </group>
          <group position={[-5055.7, 1100.3, -9.4]} scale={1.2}>
            <mesh
              geometry={nodes.round_coffee_table_001_2.geometry}
              material={materials["glass.001"]}
            />
            <mesh
              geometry={nodes.round_coffee_table_3.geometry}
              material={materials.round_coffee_table}
            />
          </group>
          <group position={[-4801.8, 331.1, -10.9]}>
            <mesh
              geometry={nodes.Scene018.geometry}
              material={materials["metal.001"]}
            />
            <mesh
              geometry={nodes.Scene018_1.geometry}
              material={materials["glass.001"]}
            />
          </group>
          <mesh
            geometry={nodes.pouf_2.geometry}
            material={materials.pouf_3}
            position={[-5471.1, 736.8, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__10_.geometry}
            material={materials.pouf_3}
            position={[-4958.5, 1104.8, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__11_.geometry}
            material={materials.pouf_3}
            position={[-5151.1, 1104.8, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__1_.geometry}
            material={materials.pouf_3}
            position={[-5278.5, 736.8, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__2_.geometry}
            material={materials.pouf_3}
            position={[-5386, 836, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__3_.geometry}
            material={materials.pouf_3}
            position={[-5386, 628.2, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__4_.geometry}
            material={materials.pouf_3}
            position={[-5035.5, 304.4, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__5_.geometry}
            material={materials.pouf_3}
            position={[-5035.5, 512.2, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__6_.geometry}
            material={materials.pouf_3}
            position={[-4928, 413, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__7_.geometry}
            material={materials.pouf_3}
            position={[-5120.6, 413, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__8_.geometry}
            material={materials.pouf_3}
            position={[-5066, 996.2, -6.4]}
          />
          <mesh
            geometry={nodes.pouf_2__9_.geometry}
            material={materials.pouf_3}
            position={[-5066, 1204, -6.4]}
          />
        </group>
      </group>
      <group position={[453, -873, -10.3]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Scene009.geometry} material={materials.metal} />
        <mesh geometry={nodes.Scene009_1.geometry} material={materials.glass} />
      </group>
    </group>
  );
};

export default PlatinumStall;
useGLTF.preload(".stalls/platinumStall.gltf");
